image:
  file: .gitpod.Dockerfile

tasks:
  - init: CYPRESS_CACHE_FOLDER=$GITPOD_REPO_ROOT/.tmp/cypress npm install
    command: export CYPRESS_CACHE_FOLDER=$GITPOD_REPO_ROOT/.tmp/cypress && sails lift

ports:
  - port: 1337
    onOpen: open-browser

vscode:
  extensions:
    - esbenp.prettier-vscode@5.7.1:GDba64T6G+TUi1qmc6BE3A==
