name: dev
on:
    push:
        branches: [dev]
    pull_request:
        branches: [dev]
jobs:
    qa:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Run HTML checks
              run: "npm run qa:html"

            - name: Run JavaScript checks
              run: "npm run qa:js"

            - name: "Run Cypress tests in dev setup"
              uses: cypress-io/github-action@v2
              env:
                  PORT: 1338
              with:
                  record: false
                  quiet: true
                  command-prefix: npx
                  start: sails lift
                  wait-on: "http://localhost:1338"
