name: dev
on:
    push:
        branches: [dev]
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  record: false
                  quiet: true
                  start: npx sails lift --port 1338
                  wait-on: "http://localhost:1338"
