name: prod
on:
    push:
        branches: [prod]
    pull_request:
        branches: [prod]
jobs:
    cypress:
        runs-on: ubuntu-latest
        environment: prod
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Run Cypress tests
              uses: cypress-io/github-action@v2
              env:
                  NODE_ENV: production
                  sails_session__cookie__secure: false
                  sails_http__trustProxy: true
                  sails_session__url: ${{ secrets.REDIS_URL }}
                  sails_datastores__default__adapter: "sails-mongo"
                  sails_datastores__default__url: ${{ secrets.MONGO_URL }}
              with:
                  record: false
                  quiet: true
                  command-prefix: npx
                  start: node app --port 1338
                  wait-on: "http://localhost:1338"
