name: staging
on:
    push:
        branches: [staging]
    pull_request:
        branches: [staging]
jobs:
    qa:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Run HTML checks
              run: "npm run qa:html"

            - name: Run JavaScript checks
              run: "npm run qa:js"

            - name: "Run Cypress tests; code: development, db: Mongo (staging), session store: sails"
              uses: cypress-io/github-action@v2
              env:
                  NODE_ENV: staging
                  sails_datastores__default__adapter: "sails-mongo"
                  sails_datastores__default__url: ${{ secrets.MONGO_URL }}
              with:
                  record: false
                  quiet: true
                  command-prefix: npx
                  start: node app --port 1338
                  wait-on: "http://localhost:1338"
