name: staging
on:
    push:
        branches: [staging]
    pull_request:
        branches: [staging]
jobs:
    cypress:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Run Cypress tests
              uses: cypress-io/github-action@v2
              env:
                  NODE_ENV: staging
              with:
                  record: false
                  quiet: true
                  start: node app --port 1338
                  wait-on: "http://localhost:1338"
