name: staging
on:
    push:
        branches: [staging, prod]
    pull_request:
        branches: [staging, prod]
    workflow_dispatch:
    
jobs:
    qa:
        runs-on: ubuntu-latest
        services:
            redis:
                image: redis
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 6379:6379
        steps:
            - name: Checkout code
              uses: actions/checkout@v1

            - name: Run HTML checks
              run: "npm run qa:html"

            - name: Run JavaScript checks
              run: "npm run qa:js"

            - name: "Run Cypress tests in staging setup"
              uses: cypress-io/github-action@v2
              env:
                  PORT: 1338
                  sails_session__cookie__secure: false
                  sails_session__url: "redis://localhost:6379"
                  sails_http__trustProxy: true
                  sails_datastores__default__adapter: "sails-mongo"
                  sails_datastores__default__url: ${{ secrets.MONGO_STAGING_URL }}
              with:
                  record: false
                  quiet: true
                  command-prefix: npx
                  start: npm start
                  wait-on: "http://localhost:1338"
